excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Christina-Napier.github.io
title: Chrissy @SecAssistance
tagline: My mind dump
description: Computer Security and Forensics nerd
paginate: 5
