excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Christina-Napier.github.io
title: Christina-Napier
tagline: A log of everyday life
description: My awesome new site
paginate: 5